// <auto-generated />
using System;
using CCSInventory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CCSInventory.Migrations
{
    [DbContext(typeof(CCSDbContext))]
    [Migration("20181018123018_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("CCSInventory.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Note");

                    b.Property<string>("PasswordHash");

                    b.Property<int>("Role");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasAlternateKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new { ID = 1L, Created = new DateTime(2018, 10, 18, 12, 30, 18, 51, DateTimeKind.Utc), CreatedBy = "Seeded Data", FirstName = "Weber", LastName = "CS", Modified = new DateTime(2018, 10, 18, 12, 30, 18, 51, DateTimeKind.Utc), ModifiedBy = "Seeded Data", Note = "Default user for an empty database", PasswordHash = "$2a$10$/n.xV7jA5piJOZmfbT270eAKstycJ9WHqfpSttqz25ARWwnyLCyhu", Role = 3, UserName = "skram" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
